### ISSUE TITLE
civic.load_cache() is broken

### ISSUE THREAD

**Issue by mapo9** [griffithlab/civicpy#141]
Hi, 
since today `civic.load_cache()` doesnt work.
It doesn't fail but ends in the following loop that goes on and on and on:

`WARNING:root:Local cache at /Users/students/.civicpy/cache.pkl is stale, updating from remote.
WARNING:root:Downloading remote cache from https://civicdb.org/downloads/nightly/nightly-civicpy_cache.pkl.
WARNING:root:Local cache at /Users/students/.civicpy/cache.pkl is stale, updating from remote.
WARNING:root:Downloading remote cache from https://civicdb.org/downloads/nightly/nightly-civicpy_cache.pkl.
WARNING:root:Local cache at /Users/students/.civicpy/cache.pkl is stale, updating from remote.
WARNING:root:Downloading remote cache from https://civicdb.org/downloads/nightly/nightly-civicpy_cache.pkl.`

**Comment by susannasiebert** [comment]
Thanks for reporting this problem with us. The remote cache pkl file has been regenerated, which should fix this issue. Please give it another try and let me know if you run into any issues.

**Comment by mapo9** [comment]
Thanks. It's working again
