### ISSUE TITLE
civicpy-specific endpoints on CIViC production

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/civicpy#69]
Currently, we do some very large (and low-count) requests. This might not be captured by CIViC's [throttling mechanism](https://griffithlab.github.io/civic-api-docs/#throttling), which is request count based. We may want to consider the strategies to mitigate widespread adoption of CIViCpy, particularly if we fail to update our nightly civicpy cache and clients revert to hard (API-driven) updates.

@susannasiebert and @acoffman what do you think?

**Comment by ahwagner** [comment]
@acoffman has suggested elsewhere that we consider civicpy-specific endpoints. Renaming issue to reflect this proposal.

**Comment by susannasiebert** [comment]
This has been superseded by https://github.com/griffithlab/civicpy/issues/108
